image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run Spring Boot Application
    command: ./gradlew bootRun
    openMode: split-right  # Changed from split-bottom

ports:
  - port: 8080
    onOpen: open-browser
    name: Spring Boot App
  - port: 8081
    onOpen: open-preview
    name: H2 Console

